id: OauthRefreshToken
description: OAuth2 refresh token
storage: Internal
properties:
  token:
    type: string
  client:
    $ref: '#/definitions/OauthClient'
  expires:
    type: integer
  user:
    $ref: '#/definitions/User'
  scope:
    type: string
  created:
    type: integer
required:
  - token
  - client
  - expires
  - user
  - cope
  - created
