id: OauthAccessToken
description: OAuth2 access token
storage: Internal
properties:
  token:
    type: string
    maxLength: 255
  client:
    $ref: '#/definitions/OauthClient'
  expires:
    type: integer
  user:
    $ref: '#/definitions/User'
  scope:
    type: string
  session:
    $ref: '#/definitions/UserSession'
  created:
    type: integer
required:
  - token
  - client
  - expires
  - user
  - scope
  - created
