id: UserSession
description: User session token
storage: Internal
properties:
  token:
    type: string
  user:
    $ref: '#/definitions/User'
  expires:
    type: integer
  created:
    type: integer
required:
  - token
  - user
  - expires
  - created
